apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release1.yaml
  - release2.yaml

patches:
- patch: |-
    - op: add
      path: /spec/dependsOn
      value:
        - name: sync-wave1
  target:
    kind: HelmRelease

- patch: |-
    - op: add
      path: /spec/dependsOn/1
      value:
        - name: sync-wave2
  target:
    kind: HelmRelease
    annotationSelector: "sync-wave=2"

- patch: |-
    - op: add
      path: /spec/dependsOn/1
      value:
        - name: sync-wave3
  target:
    kind: HelmRelease
    annotationSelector: "sync-wave=3"

- patch: |-
    - op: add
      path: /spec/dependsOn/1
      value:
        name: sync-wave4
  target:
    kind: HelmRelease
    annotationSelector: "sync-wave=4"

- patch: |-
    - op: add
      path: /spec/dependsOn/1
      value:
        name: sync-wave5
  target:
    kind: HelmRelease
    annotationSelector: "sync-wave=5"


configMapGenerator:
- name: dependencies
  envs:
  - syncwaves.env
generatorOptions:
  disableNameSuffixHash: true

replacements:
  - path: ./syncwaves/wave1.yaml
  - path: ./syncwaves/wave2.yaml
  - path: ./syncwaves/wave3.yaml
  - path: ./syncwaves/wave4.yaml
  - path: ./syncwaves/wave5.yaml